### PR TITLE
Implement accessibility support for solr facets.

### PR DESCRIPTION
**Pull request by bierik**
According to access4all the facets of the solr search has to be
reachable with the keyboard.

Go trough the filter by hitting tab. This will focus the filter.

Controls on the filter:
- right arrow: open the focused filter
- down arrow: open the focused filter
- enter: open the focused filter

Controls on open filter:
- escape: close the open filter 
- left arrow: close the open filter
- down arrow: focus next facet
- up arrow: focus previous facet

facets_accessiblity

### CODE REVIEW

**Comment by bierik** [comment]
@maethu HTML and changelog added

**Comment by maethu** [comment]
@bierik The browser window moves down on certain "down arrow" clicks. 

screen shot 2016-02-23 at 09 34 04

**Comment by maethu** [comment]
pls rebase too.

**Comment by maethu** [comment]
@bierik How can I select/choose a facet?

**Comment by bierik** [comment]
@maethu updated

**Comment by maethu** [comment]
@bierik Removing a facet has still the `rel`attribute?

**Comment by maethu** [comment]
Searching is no longer possible?????? Seems like the enter key no longer works. 

pls fix asap!

**Comment by bierik** [comment]
@maethu 
I got out of control when trying to style the search form. The nesting in the current implementation is too deep to predict the impacts when touching the styles. So in https://github.com/4teamwork/ftw.solr/commit/f2289c4d14817cec2c623ddb8973b05fb1e2069f I tried to rewrite the styling to make it less complex. I removed the `.no-border` style definition because I don't know what this thing is doing actually.

**Comment by maethu** [comment]
It's OK to change things... but ftw.solr is used in several environments, for example with plonetheme.onegov. Markup changes makes it hard to keep up :disappointed_relieved: 

I'm not sure how to deal with this...
But usually if you change the markup we need to change a lot of things, like every theme we have in use.

**Comment by maethu** [comment]
I'll added to fixes to your branch:
- remove rel att from a tag and readd is as text node
- Fix selected faces css selector

**Pull request merged**
