### PR TITLE
Python 3.8, 3.9 support an tests against Plone 6a3

### PR DESCRIPTION
**Pull request by maethu**

### CODE REVIEW

**Comment by maethu** [comment]
@buchi Any idea the `which` statement fails within the make file? The corresponding line is https://github.com/4teamwork/ftw.solr/pull/188/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R123

It does work without any problems on my local machine. With venv / without venv / full path / etc.

**Comment by buchi** [comment]
@maethu thanks for your work!

We currently don't want to switch to a Makefile based build system, but stick with our existing approach.
We will amend your PR and try to get it merged this sprint.

**Comment by maethu** [comment]
> @maethu thanks for your work!
> 
> We currently don't want to switch to a Makefile based build system, but stick with our existing approach. We will amend your PR and try to get it merged this sprint.

@buchi Thank you very much!

But you can also discard this PR, I moved in the meanwhile to elasticsearch.
So if you guys can use it, I'm happy to help! But there is no urgency on my end :-)

**Comment by lukasgraf** [comment]
Superseded by https://github.com/4teamwork/ftw.solr/pull/195

**Pull request closed without merging**
